import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {Header} from "../components/Header";
import {Content} from "../components/Conten";
import {GetServerSideProps, NextPage} from "next";
import {IDataDto, IItemsDto} from "../utils/api/types";
import {ItemsApi} from "../utils/api/items";
import {wrapper} from "../redux/store";
import {setItems, setMeta} from '../redux/itemsSlice';
import {Html} from "next/document";
import {Api} from '../utils/api';
import { setUserData } from '../redux/userSlice';

interface HomeProps {
    items: IDataDto
}

const Home: NextPage<HomeProps> = ({items}) => {

    console.log(items, 963852)

    return (
        <div>
                <Head>
                    <title>Seedra</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/headerIcon/tabLogo.svg"/>
                    <link rel="preconnect" href="https://fonts.googleapis.com"/>
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={''}/>
                    <link
                        href="https://fonts.googleapis.com/css2?family=Lexend:wght@300;400;500;600;700;900&display=swap"
                        rel="stylesheet"/>
                </Head>


            <div className={styles.wrapper}>

                <div className={'container'}>
                    <main className={styles.main}>

                        <Header/>

                        <Content meta={items.meta} items={items.items}/>
                        {/* <Cart/>*/}
                        {/* <Cart/>*/}
                    </main>
                    {/*<footer className={styles.footer}>
                        <Footer/>
                    </footer>*/}
                </div>

            </div>
        </div>

    )
}


export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps(store => async (ctx) => {

    try {

        const items = await Api().items.getAll()

        const userData = await Api(ctx).user.getMe()
        store.dispatch(setUserData(userData))
        store.dispatch(setItems(items.items))
        store.dispatch(setMeta(items.meta))
        console.log(items.meta, 14785)
        return {
            props: {
                items,
                userData
            }
        }
    } catch (e) {
        console.log(e)
    }
    return {
        props: {
            items: null
        }
    }

})


export default Home